### ISSUE TITLE
가상계좌 환불 시 오류 발생합니다.

### ISSUE THREAD

**Issue by mummumm** [kginicis-ts/INICIS_Billing#14]
안녕하세요. 현재 pc 가상계좌 전체환불 테스트 중 질문이 있어 문의드립니다.
가상계좌 전체환불 시 아래와 같은 오류가 발생합니다.

환불 실패: {"resultCode":"330198","resultMsg":"기타 에라"}

요청 데이터는 정확히 입력하였으며 Hash 알고리즘도 홈페이지에 제공되는 데이터 암호화와 샘플 코드로 테스트한 데이터 모두 정상적으로 동작하는데 위 같은 에러가 왜 발생하는걸까요?

답변부탁드립니다. 감사합니다.

**Comment by ts-inicis** [comment]
문의주신 오류코드 기준 안내드립니다. 
330198 오류코드는 보통적으로 인입된 환불계좌정보가 정상적이지 않은 경우, 발생되는 오류코드입니다. 
전달주신 환불계좌정보가 정상적인 환불계좌정보인지 확인부탁드립니다. 
추가 상세 확인이 필요한 경우, ts@kggroup.co.kr 로 요청 데이터 전달주시면 추가 확인 도와드리겠습니다.
